bank_website/bank_website/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bankingapp.urls')),
    path('credentials/',include('credentials.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bank_website/bankingapp/urls.py
from django.urls import path
from .import views
app_name='bankingapp'

urlpatterns=[
    path('', views.index,name='index'),
    path('new/',views.new,name='new'),
    path('add/',views.person_create_view, name='person_add'),
    path('ajax/load-areas/',views.load_areas, name='ajax_load_areas'),
    path('submit/',views.submit,name='submit'),
]

bank_website/credentials/urls.py
from django.urls import path
from .import views
app_name='credentials'

urlpatterns=[
    path('register',views.register,name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
]

bank_website/bankingapp/models.py
from django.db import models

# Create your models here.
class District(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    link=models.CharField(max_length=250,unique=True)

    class Meta:
        ordering=('name',)
        verbose_name='district'
        verbose_name_plural='districts'

    def __str__(self):
        return '{}'.format(self.name)

class Branch(models.Model):
    district=models.ForeignKey(District,on_delete=models.CASCADE)
    slug=models.SlugField(max_length=250,unique=True)
    area=models.CharField(max_length=250,unique=True)

    class Meta:
        ordering=('area',)
        verbose_name='branch'
        verbose_name_plural='branches'

    def __str__(self):
        return '{}'.format(self.area)

class Person(models.Model):
    GENDER_CHOICES = [

        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Other', 'Other')
    ]
    name=models.CharField(max_length=250,unique=True)
    dob=models.DateField(null=True,blank=True)
    age=models.IntegerField()
    gender = models.CharField(choices=GENDER_CHOICES, max_length=200, null=True)
    phoneno = models.CharField(max_length=250,unique=True)
    email=models.CharField(max_length=250,unique=True)
    address = models.TextField()
    district=models.ForeignKey(District, on_delete=models.SET_NULL, blank=True, null=True)
    area=models.ForeignKey(Branch, on_delete=models.SET_NULL, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{}'.format(self.name)

bank_website/credentials/models.py
from django.db import models

# Create your models here.

bank_website/bankingapp/forms.py
from django import forms
from .models import Person, Branch
class PersonCreationForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = '__all__'

        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control'}),
            'age': forms.NumberInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'dob': forms.DateInput(attrs={'class': 'form-control','type':'date'}),
            'phoneno': forms.TextInput(attrs={'class': 'form-control'}),
            'address': forms.Textarea(attrs={'class': 'form-control'}),
            'gender': forms.Select(attrs={'class': 'form-control'}),
            'district': forms.Select(attrs={'class': 'form-control'}),
            'area': forms.Select(attrs={'class': 'form-control'}),
                  }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['area'].queryset = Branch.objects.none()

        if 'district' in self.data:
            try:
                district_id = int(self.data.get('district'))
                self.fields['area'].queryset = Branch.objects.filter(district_id=district_id).all()
            except (ValueError, TypeError):
                pass

bank_website/bankingapp/views.py
# Create your views here.
from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404,redirect
from .forms import PersonCreationForm
from .models import District,Branch,Person

# Create your views here.
def index(request):
    return render(request,"index.html")


def new(request):
    return render(request,'new_page.html')

def person_create_view(request):
    form = PersonCreationForm()
    if request.method == 'POST':
        form = PersonCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('bankingapp:submit')
    return render(request, 'submission_form.html', {'form': form})

def load_areas(request):
    district_id = request.GET.get('district_id')
    cities = Branch.objects.filter(district_id=district_id).all()
    return render(request, 'area_dropdown_list.html', {'cities': cities})

def submit(request):
    return render(request,"submit.html")

bank_website/credentials/views.py
# Create your views here.
from django.contrib import messages,auth
from django.shortcuts import redirect,render
from django.contrib.auth.models import User

# Create your views here.



def register(request):
    if  request.method == 'POST':
        username=request.POST['UserName']
        firstname=request.POST['First_Name']
        lastname=request.POST['Last_Name']
        email=request.POST['Email']
        password=request.POST['Password']
        cpassword=request.POST['Password1']

        if password==cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request,"username is already taken")
                return redirect('credentials:register')
            elif User.objects.filter(email=email).exists():
                messages.info(request,"email is already taken")
                return redirect('credentials:register')
            else:
                user=User.objects.create_user(username=username,first_name=firstname,last_name=lastname,email=email,password=password)
                user.save();
                return redirect('credentials:login')
        else:
            messages.info(request,'incorrect password')
            return redirect('credentials:register')
        return redirect('/')
    return render(request,'register.html')

def login(request):
    if  request.method == 'POST':
        username=request.POST['UserName']
        password=request.POST['Password']
        user=auth.authenticate(username=username,password=password)
        
        if user is not None:
            auth.login(request,user)
            return redirect('/')
        else:
            messages.info(request,'incorrect credentials')
            return redirect('credentials:login')

    return render(request,'login.html')


def logout(request):
    auth.logout(request)
    return redirect('/')

bank_website/templates/area_dropdown_list.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.area }}</option>
{% endfor %}

bank_website/templates/login.html
{% load static %}
    <!DOCTYPE html>
    <!-- Website - www.codingnepalweb.com -->
    <html lang="en">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Form Validation in HTML | CodingNepal</title>
        <link rel="stylesheet" href="{% static 'assets/css/register.css'%}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
        <!-- Fontawesome CDN Link For Icons -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" />
        
      </head>
      <body>
        
        <form action="{% url 'credentials:login'%}" method='POST'>
            {% csrf_token %}
          <h2><b>Login page</b></h2>
          <div class="form-group fullname">
            <label for="username">User Name</label>
            <input type="text" name="UserName" id="username" placeholder="Enter your user name">
          </div>
          <div class="form-group password">
            <label for="password">Password</label>
            <input type="password" name="Password" id="password" placeholder="Enter your password">
            <i id="pass-toggle-btn" class="fa-solid fa-eye"></i>
          </div>
          <div class="text-center">
            click here to <a href="{% url 'credentials:register' %}">Register</a>
           </div>
          <div class="form-group submit-btn">
            <input type="submit" text="Log in">
          </div> 
        </form>
      
      </body>
    </html>

bank_website/templates/new_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="container">
        <div class="row">
          <br>
      <h1 class="head1" style="text-align:center;font-size:34px;color:blue;font-style:italic;font-weight:bold"><u>Form Submission</u></h1><br><br>
        </div>
        <img src="https://png.pngtree.com/png-clipart/20221001/original/pngtree-digital-internet-banking-application-for-financial-operation-png-image_8649134.png" alt="image" width="100%" height="450px">
        <br>
        <a href="{% url 'bankingapp:person_add' %}" class="btn btn-warning" style="font-size:20px;margin-left:530px;">Please Fill The Form</a>
      </div>
</body>
</html>

bank_website/templates/register.html
{% load static %}
<!DOCTYPE html>
<!-- Website - www.codingnepalweb.com -->
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Form Validation in HTML | CodingNepal</title>
  <link rel="stylesheet" href="{% static 'assets/css/register.css'%}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  <!-- Fontawesome CDN Link For Icons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" />

</head>

<body>

  <form action="{% url 'credentials:register'%}" method='POST'>
    {% csrf_token %}
    <h2><b>Registration Form</b></h2>
    <div class="form-group fullname">
      <label for="username">User Name</label>
      <input type="text" name="UserName" id="username" placeholder="Enter your user name">
    </div>
    <div class="form-group fullname">
      <label for="firstname">First Name</label>
      <input type="text" name="First_Name" id="firstname" placeholder="Enter your first name">
    </div>
    <div class="form-group fullname">
      <label for="lastname">Last Name</label>
      <input type="text" name="Last_Name" id="lastname" placeholder="Enter your last name">
    </div>
    <div class="form-group email">
      <label for="email">Email Address</label>
      <input type="text" name="Email" id="email" placeholder="Enter your email address">
    </div>
    <div class="form-group password">
      <label for="password">Password</label>
      <input type="password" name="Password" id="password" placeholder="Enter your password">
      <i id="pass-toggle-btn" class="fa-solid fa-eye"></i>
    </div>
    <div class="form-group password">
      <label for="password">Confirm Password</label>
      <input type="password" name="Password1" id="password" placeholder="Confirm your password">
      <i id="pass-toggle-btn" class="fa-solid fa-eye"></i>
    </div>
    <div class="form-group submit-btn">
      <input type="submit">
    </div>

  </form>

  {% for msg in messages %}
  
    <div class="info-box">
      <div class="w3-panel w3-yellow">
        <h3 style="color:rgb(255, 255, 255);font-size:30px;font-weight:bold;">Warning!</h3>
        <p style="color:rgb(255, 255, 255);font-size:30px;">{{msg}}</p>
      </div>
    </div>
  {% endfor %}
</body>

</html>

bank_website/templates/submission_form.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>

<body>
    <div class="container">
        <div class="row">
            <br>
            <h1 class="head1" style="text-align:center;font-size:34px;color:rgb(253, 102, 2);font-style:italic;font-weight:bold">
                <u>Form Submission</u></h1><br><br>
            <br>
            <form method="post" id="personForm" data-cities-url="{% url 'bankingapp:ajax_load_areas' %}">
                {% csrf_token %}
                <div class="container">
                    {{ form.as_p }}
                    <div class="form-group row">
                        <div class="col-sm-2">Account Type</div>
                        <div class="col-sm-10">
                            <select>
                                <option value>Savings</option>
                                <option value>Current</option>
                            </select>
                        </div>
                    </div>

                    <br>
                    <div class="form-group row">
                        <div class="col-sm-2">Materials Provide</div>
                        <div class="col-sm-10">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" id="gridCheck1">
                                <label class="form-check-label" for="gridCheck1">Debit Card </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" id="gridCheck2">
                                <label class="form-check-label" for="gridCheck1">Credit Card </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" id="gridCheck3">
                                <label class="form-check-label" for="gridCheck1">Cheque Book </label>
                            </div>
                        </div>
                    </div>
                    <br><br><br>
                    <input type="submit" class="btn btn-primary" value="Submit"
                        style="font-size:18px;margin-left:100px;">
                </div>
            </form>
        </div>
    </div>
            <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
            <script>
                $("#id_district").change(function () {
                    const url = $("#personForm").attr("data-cities-url");  // get the url of the `load_areas` view
                    const districtId = $(this).val();  // get the selected district ID from the HTML input

                    $.ajax({                       // initialize an AJAX request
                        url: url,                    // set the url of the request (= /persons/ajax/load-areas/ )
                        data: {
                            'district_id': districtId       // add the district id to the GET parameters
                        },
                        success: function (data) {   // `data` is the return of the `load_cities` view function
                            $("#id_area").html(data);  // replace the contents of the area input with the data that came from the server

                        }
                    });

                });
            </script>
      

</body>

</html>

bank_website/templates/submit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
        <div class="container">
          <div class="row">
            <div class="mx-auto">
                <div class="card mb-3">
                  {% if user.is_authenticated %}
                  <li class="nav-item" style="color:rgb(255, 60, 16);font-size:34px;font-weight:bold"><u><a class="nav-link"
                    href="{% url 'credentials:logout'%}">Logout</a></u></li>
                  {% endif %}
                    <img class="card-img-top" src="{% static 'assets/img/handshake.jpg'%}" alt="Card image cap" width="100%" height="800px">
                    <div class="card-body">
                      <a class="card-title" style="text-align:center;font-size:34px;color:rgb(255, 106, 0);font-style:normal;font-weight:bold">Form Submission was Successful</a>
                      <br>
                      <br>
                      <a href="{% url 'bankingapp:index' %}" style="text-align:center;font-size:25px;color:rgb(0, 89, 255);font-style:normal">Return Home Page</a>
                    </div>
                  </div>
          </div>
        </div>
      </div>
    </div>
</body>
</html>